/**
 * Opens a real PR documenting the schema change, using the plain GitHub
 * REST API (no octokit dependency needed for three calls). Guarded by
 * env -- if GITHUB_TOKEN / GITHUB_PR_REPO aren't set, applyChange() still
 * runs the real archive/drop against the demo DB, it just skips the PR
 * step and says so.
 */

const API = 'https://api.github.com';

export interface SchemaChangeSummary {
  archivedColumn: string;
  archivedRows: number;
  droppedColumns: string[];
}

export async function openSchemaChangePR(
  summary: SchemaChangeSummary,
): Promise<string | null> {
  const token = process.env.GITHUB_TOKEN;
  const repoSlug = process.env.GITHUB_PR_REPO; // "owner/repo", a throwaway/scratch repo you own
  if (!token || !repoSlug) return null;

  const [owner, repo] = repoSlug.split('/');
  const headers = {
    Authorization: `Bearer ${token}`,
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
  };

  const repoInfo = await json(await fetch(`${API}/repos/${owner}/${repo}`, { headers }));
  const baseBranch: string = repoInfo.default_branch;

  const baseRef = await json(
    await fetch(`${API}/repos/${owner}/${repo}/git/ref/heads/${baseBranch}`, { headers }),
  );
  const baseSha: string = baseRef.object.sha;

  const branchName = `agent/drop-unused-columns-${Date.now()}`;
  await fetch(`${API}/repos/${owner}/${repo}/git/refs`, {
    method: 'POST',
    headers,
    body: JSON.stringify({ ref: `refs/heads/${branchName}`, sha: baseSha }),
  });

  const path = `migrations/${Date.now()}_drop_unused_user_columns.sql`;
  const content = buildMigrationFile(summary);
  await fetch(`${API}/repos/${owner}/${repo}/contents/${path}`, {
    method: 'PUT',
    headers,
    body: JSON.stringify({
      message: 'Drop unused users columns',
      content: Buffer.from(content, 'utf8').toString('base64'),
      branch: branchName,
    }),
  });

  const pr = await json(
    await fetch(`${API}/repos/${owner}/${repo}/pulls`, {
      method: 'POST',
      headers,
      body: JSON.stringify({
        title: 'Drop unused columns from users table',
        head: branchName,
        base: baseBranch,
        body: buildPrBody(summary),
      }),
    }),
  );

  return pr.html_url as string;
}

function buildMigrationFile(summary: SchemaChangeSummary): string {
  const lines = [
    '-- Generated by the agent. Archived data lives in users_archive before drop.',
    ...summary.droppedColumns.map((c) => `ALTER TABLE users DROP COLUMN ${c};`),
  ];
  return lines.join('\n') + '\n';
}

function buildPrBody(summary: SchemaChangeSummary): string {
  return [
    '## What',
    `Drops ${summary.droppedColumns.length} unused columns from \`users\`: ${summary.droppedColumns.join(', ')}.`,
    '',
    '## Why',
    `\`${summary.archivedColumn}\` held ${summary.archivedRows} live rows, so a human was asked before touching it. `,
    `Decision: archive first, then drop. Archived rows are in \`users_archive\`, keyed by user id.`,
    '',
    '_Opened by the agent, approved by a human over SMS/voice._',
  ].join('\n');
}

async function json(res: Response): Promise<any> {
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`GitHub API ${res.status}: ${text}`);
  }
  return res.json();
}
